{% set name = "ph5concat" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NU-CUCIS/ph5concat/archive/refs/tags/v1.1.0.tar.gz

requirements:
  build:
    - {{ compiler('cxx') }}
    - hdf5=*=*mpich*
    - zlib

  run:
    - hdf5=*=*mpich*
    - zlib

about:
  home: https://github.com/NU-CUCIS/ph5concat
